apiVersion: v1
kind: Service
metadata:
  name: {{ include "inviso.fullname" . }}
  labels:
    {{- include "inviso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4567
      protocol: TCP
      name: custom
  selector:
    {{- include "inviso.selectorLabels" . | nindent 4 }}
